// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for interpreting tarot readings, personalizing the interpretation based on the user's booking history.
 *
 * - interpretTarotReading - The main function to initiate the tarot reading interpretation.
 * - InterpretTarotReadingInput - The input type for the interpretTarotReading function.
 * - InterpretTarotReadingOutput - The output type for the interpretTarotReading function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the tarot reading interpretation.
const InterpretTarotReadingInputSchema = z.object({
  tarotCards: z
    .string()
    .describe('The tarot cards drawn for the reading, separated by commas.'),
  bookingHistory: z
    .string()
    .describe(
      'A summary of the user booking history, including the types of readings they have had and any notes from previous sessions.'
    ),
  language: z
    .string()
    .describe('The language for the interpretation (e.g., "en", "id").'),
});
export type InterpretTarotReadingInput = z.infer<typeof InterpretTarotReadingInputSchema>;

// Define the output schema for the tarot reading interpretation.
const InterpretTarotReadingOutputSchema = z.object({
  interpretation: z
    .string()
    .describe('The AI-powered interpretation of the tarot reading, personalized based on the booking history.'),
});
export type InterpretTarotReadingOutput = z.infer<typeof InterpretTarotReadingOutputSchema>;

// Define the main function to initiate the tarot reading interpretation.
export async function interpretTarotReading(
  input: InterpretTarotReadingInput
): Promise<InterpretTarotReadingOutput> {
  return interpretTarotReadingFlow(input);
}

// Define the prompt for the tarot reading interpretation.
const prompt = ai.definePrompt({
  name: 'interpretTarotReadingPrompt',
  input: {schema: InterpretTarotReadingInputSchema},
  output: {schema: InterpretTarotReadingOutputSchema},
  prompt: `You are an expert tarot reader, skilled in providing personalized and insightful interpretations.

  Based on the tarot cards drawn and the user's booking history, provide a detailed interpretation that is relevant to their situation.

  The interpretation must be in the following language: {{{language}}}.

  Tarot Cards: {{{tarotCards}}}
  Booking History: {{{bookingHistory}}}

  Interpretation:`,
});

// Define the Genkit flow for the tarot reading interpretation.
const interpretTarotReadingFlow = ai.defineFlow(
  {
    name: 'interpretTarotReadingFlow',
    inputSchema: InterpretTarotReadingInputSchema,
    outputSchema: InterpretTarotReadingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
